### abbyyR: Access Abbyy Cloud OCR SDK via R

#### Load the package

To get started, load the package. The latest version of the package will always be on github. Instructions for installing the package from github are provided below.



```r
library(abbyyR)
```


```r
"
Get the latest version from github:

# install.packages('devtools')
devtools::install_github('soodoku/abbyyR')
"
```

#### Set credentials

Your first task on loading the package should be to set the credentials - application ID and password. If you haven't already, you can get this information 
[http://ocrsdk.com/](http://ocrsdk.com/). Once you have the application ID and password, set it via the `setapp` function. 


```r
setapp(c("factbook", "7YVBc8E6xMricoTwp0mF0aHP"))
```

#### Get Information about Application


```r
getAppInfo()
```

```
## Name of Application: factbook
## No. of Pages Remaining: 99
## No. of Fields Remaining: 495
## Application Credits Expire on: 2015-08-28T00:00:00
## Type: Normal
```

#### List Tasks 

List all the tasks -- completed, in progress, queued etc. The function returns a data frame.


```r
tasklist <- listTasks()
```

```
## Total No. of Tasks:  10 
## No. of Finished Tasks:  4 
## Task IDs: 
##  47f9b0d4-79a2-4aed-b656-2683a85ac203
##  b7cef2a3-ed10-4e36-9520-5073f2546204
##  3e292e02-8213-46b5-872a-e60f9b6eb259
##  e7049cfa-b70c-4188-934b-4064007ad52a
##  69c3ab2b-332f-4b34-9252-e4a3ea619fa1
##  a742a642-7943-4ced-bff1-5a40dcd2a5c8
##  91aaeca6-ace5-43ae-923e-87cbad943dde
##  c45b18c8-aa9d-4250-8a8d-96d6b77c1f59
##  ffbf5d30-c9b5-41f7-99c3-f3baa4b77560
##  12c6ae7f-46f2-4e38-a8dd-e405efdd973d
```

```r
listTasks(excludeDeleted="true")
```

```
## Total No. of Tasks:  8 
## No. of Finished Tasks:  4 
## Task IDs: 
##  3e292e02-8213-46b5-872a-e60f9b6eb259
##  e7049cfa-b70c-4188-934b-4064007ad52a
##  69c3ab2b-332f-4b34-9252-e4a3ea619fa1
##  a742a642-7943-4ced-bff1-5a40dcd2a5c8
##  91aaeca6-ace5-43ae-923e-87cbad943dde
##  c45b18c8-aa9d-4250-8a8d-96d6b77c1f59
##  ffbf5d30-c9b5-41f7-99c3-f3baa4b77560
##  12c6ae7f-46f2-4e38-a8dd-e405efdd973d
```

```r
listTasks(fromDate="2015-05-30T20:28:43Z", toDate="2015-05-31T20:28:43Z")
```

```
## No tasks in the application.
```

#### List Finished Tasks


```r
listFinishedTasks()
```

```
## No. of Finished Tasks:  6 
## Task IDs: 
##  5c30fd05-fb01-405a-8494-b0e8b825cd82
##  ee1f007b-50c2-4c03-a279-449be4e93e87
##  91aaeca6-ace5-43ae-923e-87cbad943dde
##  c45b18c8-aa9d-4250-8a8d-96d6b77c1f59
##  ffbf5d30-c9b5-41f7-99c3-f3baa4b77560
##  12c6ae7f-46f2-4e38-a8dd-e405efdd973d
```

#### Get Task Status


```r
getTaskStatus(taskId="47f9b0d4-79a2-4aed-b656-2683a85ac203")
```

```
## Status of the task:  Deleted
```

#### Delete Task

Deleting an already deleted task will result in an error.


```r
#deleteTask(taskId="47f9b0d4-79a2-4aed-b656-2683a85ac203")
```

**Submit an Image for Processing**

Note: I am uploading a sample image that Abbyy provides for free to test its software. You can find this image in the data folder of the package.


```r
submitImage(file_path="t1.tif", pdfPassword="")
```

```
## Status of the task:  Submitted 
## Task ID:  9c219122-ebab-4785-b2db-48482d9790e6
```

**Process an Image**


```r
processImage(file_path="t1.tif")
```

```
## Status of the task:  Queued
```
